### ISSUE TITLE
Shadowed classes of Jakarta Web Services

### ISSUE THREAD

**Issue by reitzmichnicht** [jakartaee/jax-ws-api#225]
Why does this package shadow definitions of jakarta.jws-api?
Like all classes in jakarta.jws namespace.

It would be much better and cleaner to add a dependency to jakarta.jws-api instead.

I would also assume that the module exports are conflicting between both dependencies because both export the same namespace

**Comment by lukasj** [comment]
`jakarta.jws-api` no longer exists, see https://jakarta.ee/specifications/xml-web-services/4.0/, specifically:

> folds Jakarta Web Services Metadata Specification into this/Jakarta Web Services Specification (Jakarta Web Services Metadata Specification is no longer available as a standalone API/project/jar)
